{"timestamp":"2025-10-29T21:43:31.951260","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-10-29T21:43:31.952470","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/crime_data_export.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-10-29T21:43:32.588594Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-10-29T21:43:32.589424Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-10-29T21:43:32.590066Z","level":"info","event":"Current task name:export_crime_data","chan":"stdout","logger":"task"}
{"timestamp":"2025-10-29T21:43:32.590542Z","level":"info","event":"Dag name:crime_data_export","chan":"stdout","logger":"task"}
{"timestamp":"2025-10-29T21:43:32.604913","level":"warning","event":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py:471: DeprecationWarning: Using Connection.get_connection_from_secrets from `airflow.models` is deprecated.Please use `get` on Connection from sdk(`airflow.sdk.Connection`) instead\n  warnings.warn(\n","logger":"py.warnings"}
{"timestamp":"2025-10-29T21:43:32.631771","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"AirflowNotFoundException","exc_value":"The conn_id `snowflake_conn` isn't defined","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":920,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1215,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/crime_data_export.py","lineno":36,"name":"export_crime_data"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py","lineno":407,"name":"get_conn"},{"filename":"/usr/local/lib/python3.12/functools.py","lineno":998,"name":"__get__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py","lineno":256,"name":"_get_conn_params"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py","lineno":64,"name":"get_connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py","lineno":478,"name":"get_connection_from_secrets"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/definitions/connection.py","lineno":147,"name":"get"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-10-29T21:43:32.637111","level":"error","event":"Airflow Task Failed\n    DAG: crime_data_export\n    Task: export_crime_data\n    Execution Date: None\n    Log: http://localhost:8080/dags/crime_data_export/runs/manual__2025-10-29T21%3A43%3A11.609734%2B00%3A00/tasks/export_crime_data?try_number=1\n    ","logger":"root"}
{"timestamp":"2025-10-29T21:43:32.640373Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-10-29T21:43:32.641078Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-10-29T21:43:32.641573Z","level":"info","event":"Task:<Task(PythonOperator): export_crime_data>","chan":"stdout","logger":"task"}
{"timestamp":"2025-10-29T21:43:32.642625Z","level":"info","event":"Failure caused by The conn_id `snowflake_conn` isn't defined","chan":"stdout","logger":"task"}
